#
# Model / training config with all non-path or collection params
# --------------------------------------------------------------

#
# meta stuff
#

# -1 for disabling this feature, and only run validation after every epoch
validate_every_n_batches: 10000
validation_cont_use_cache: False

token_embedder_type: "bert_cls" # embedding,fasttext,bert_cls
train_embedding: False
sparse_gradient_embedding: True

use_fp16: False

random_seed: 208973249 # real-random (from random.org)

# needs to be the same model + model_config + token_embedder_type + vocabulary!
# ATTENTION !! this makes reproducability awfully difficult 
#warmstart_model_path: "/data01/hofstaetter/msmarco-passage-experiments/2019-07-22_1456_bert_large_cont/best-model.pytorch-state-dict"
#warmstart_model_path: "/data01/hofstaetter/ir-project-matchmaker-experiments/2019-06-06_0139_bert_cls_trainable_lowlr/best-model.pytorch-state-dict"
#warmstart_model_path: /data01/hofstaetter/trec-car-experiments/2019-08-11_1659_bert_large_cont/best-model.pytorch-state-dict
#warmstart_model_path: /data01/hofstaetter/msmarco-passage-experiments/2019-09-08_1753_bert_large_cont3/best-model.pytorch-state-dict
#warmstart_model_path: /data01/hofstaetter/msmarco-passage-experiments/2019-08-01_2109_bert_base_cont/best-model.pytorch-state-dict

#
# Models
# -------------------------------------------------------
# * Duet + Pacrr need a min_doc/query_length set
#
# * bert_cls also needs the token_embedder_type=bert_cls, as this will shake things up quite a bit 
#

#model: "Matchmaker_light_v4b" # available: knrm, conv_knrm, conv_knrm_same_gram, match_pyramid, knrm_ln, mv_lstm, pacrr,co_pacrr,duet,Matchmaker_light_v6a
#model: "conv_knrm" 
#model: "knrm" 
#model: "pacrr" 
#model: "TK_v2"
model: "bert_cls" 
#model: "duet" 
#model: "co_pacrr" 

#
# optimization
#

validation_metric: "MRR@10"

optimizer: "adam"

# default group (all params are in here if not otherwise specified in param_group1_names)
param_group0_learning_rate: 0.000003 #0.001
param_group0_weight_decay: 0.01

param_group1_names: ["stacked_att"] #dense stacked_att
param_group1_learning_rate: 0.0001
param_group1_weight_decay: 0

embedding_optimizer: "sparse_adam"
embedding_optimizer_learning_rate: 0.001
embedding_optimizer_momentum: 0.8 # only when using sgd

# disable with factor = 1 
learning_rate_scheduler_patience: 3 # * validate_every_n_batches = batch count to check
learning_rate_scheduler_factor: 0.5

#
# train loop settings
#
epochs: 1
batch_size_train: 8
batch_size_eval: 32

gradient_accumulation_steps: 8

early_stopping_patience: 5 # * validate_every_n_batches = batch count to check

#
# data loading settings
#

# max sequence lengths, disable cutting off with -1
max_doc_length: 300
max_query_length: 30

# min sequence lengths, disable cutting off with -1 , some models (paccr,duet) need this 
#min_doc_length: 200
min_doc_length: -1
#min_query_length: 30
min_query_length: -1

#
# interpretability / secondary output 
#

secondary_output:
  top_n: 10

#
# per model params: specify with modelname_param: ...
# ----------------------------------------------------
#

tk_att_heads: 16
tk_att_layer: 2
tk_att_proj_dim: 32
tk_att_ff_dim: 100

tk_kernels_mu: [1.0, 0.9, 0.7, 0.5, 0.3, 0.1, -0.1, -0.3, -0.5, -0.7, -0.9]
tk_kernels_sigma: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

#tk_kernels_mu: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.3, 0.1, -0.1, -0.3, -0.5, -0.7, -0.9]
#tk_kernels_sigma: [0.05, 0.05, 0.05, 0.05, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

#tk_kernels_mu: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5,0.4, 0.3, 0.2, 0.1, 0, -0.1, -0.2, -0.3,-0.4, -0.5,-0.6, -0.7,-0.8, -0.9, -1]
#tk_kernels_sigma: [0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043,0.043]


knrm_kernels: 11

conv_knrm_ngrams: 3
conv_knrm_kernels: 11
conv_knrm_conv_out_dim: 128 # F in the paper 

match_pyramid_conv_output_size : [16,16,16,16,16] 
match_pyramid_conv_kernel_size : [[3,3],[3,3],[3,3],[3,3],[3,3]]
match_pyramid_adaptive_pooling_size: [[36,90],[18,60],[9,30],[6,20],[3,10]]

mv_lstm_hidden_dim: 32
mv_top_k: 10

pacrr_unified_query_length: 30
pacrr_unified_document_length: 200
pacrr_max_conv_kernel_size: 3
pacrr_conv_output_size: 32
pacrr_kmax_pooling_size: 5

salc_conv_knrm_kernels: 11
salc_conv_knrm_conv_out_dim: 128
salc_conv_knrm_dropi: 0 
salc_conv_knrm_drops: 0
salc_conv_knrm_salc_dim: 300

salc_knrm_kernels: 11
salc_knrm_dropi: 0
salc_knrm_drops: 0
salc_knrm_salc_dim: 300

mm_light_kernels: 11